<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
  margin-left: 50%;
  transform: translate(-50%);
  width: 50%;
}
</style>
</head>
<body>

<h1 align="center">Customer Feedback</h1>

<div class="container">
  <form class="form" action="<?php echo $this->getUrl('feedback/index/save', ['_secure' => true]);?>" method="post">
    
    <label for="fname">First Name</label>
    <input type="text" id="name" name="name" placeholder="Your name..">

    <label for="email">Email</label>
    <input type="text" id="email" name="email" placeholder="Your E_mail..">


    <label for="mobile_no">Mobile_No</label>
    <input type="text" id="mobileno" name="mobileno" placeholder="Your Phone Number..">


    <label for="subject">Comment</label>
    <textarea id="comment" name="comment" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">

  </form>
</div>

</body>
</html>
