<?php
    /** @var \Searchanise\SearchAutocomplete\Block\Jsinit $block */
    $configuration = $block->getConfiguration();
    $widgetLink = $block->getWidgetLink();

    if (empty($configuration)) {
        return;
    }
?>

<script>
    window.Searchanise = <?php /* @noEscape */ echo json_encode($configuration); ?>;

    requirejs.config({
        paths: {
            'searchanise': '<?php echo /* @noEscape */ $widgetLink; ?>'
        },
        shim: {
            'searchanise': ['jquery']
        }
    });
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "searchanise": {}
        }
    }
</script>
