<?php
   $General = $block->GeneralUrl();
   $customer = $block->CustomerUrl();
   $order =  $block->OrderUrl();
   $Product =  $block->ProductUrl();
   $chatbotname =  $block->getName();
   $data = $block->getChat();
   // foreach($data as $d){   
   //    $a = $d->getmessage();
   //    $a = json_decode($a);
   //    echo "shubham";
   //    foreach($a as $k) {
   //       echo "<pre>";
   //       print_r($k); 

   //    }
   // }
   // // die();
?>
<input type="text" id="url" value="<?php echo $block->getStoreUrl(); ?>">
<div class="bubble open-button" style="background: rgb(0, 108, 255);" onclick="openForm()">
   <svg width="100%" height="100%" viewBox="0 0 30 33" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" clip-rule="evenodd" d="M21.333 26.324l6.449 6.376a.752.752 0 001.28-.535V21.44l-7.729 4.884z" fill="#ffffff"></path>
      <path d="M3.946 0h22.109a3.008 3.008 0 013.008 3.008V21.44l-7.624 5.004H3.945a3.008 3.008 0 01-3.007-3.008V3.008A3.008 3.008 0 013.946 0z" fill="#ffffff"></path>
      <path fill-rule="evenodd" clip-rule="evenodd" d="M21.439 26.444L.937 4.981v21.463H21.44z" fill="url(#gradient)"></path>
      <defs>
         <linearGradient id="gradient" x1="13.451" y1="12.325" x2="5.559" y2="22.297" gradientUnits="userSpaceOnUse">
            <stop stop-color="#000000" stop-opacity=".2"></stop>
            <stop offset="1" stop-color="transparent" stop-opacity="0"></stop>
         </linearGradient>
      </defs>
   </svg>
</div>
<div class="chat-popup" id="myForm">
   <form action="#" class="form-container" id="mainform">
      <div  class="top">
         <div class="avatar"> 
            <img src="<?php echo $this->getViewFileUrl('Elsnertech_Chatboat::images/logo.png'); ?>" />
         </div>
         <div class="header">
            <h1><?php echo $chatbotname; ?></h1>
         </div>
         <div data-size="normal" class="tpl-close btn cancel" onclick="closeForm()">
            <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
               <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" fill="#5e6165"></path>
            </svg>
         </div>
      </div>
      <div class="convo">
         <div class="msg-wrap">
            <?php foreach ($data as $data1): ?>
               <?php $a = $data1->getmessage();    
                     $a1 = json_decode($a,true); ?>
               <?php if(!empty($a1)): ?>

               <?php foreach ($a1 as $message): ?>
                  <?php if(strpos($message, 'receiver.') !== false): ?>
                  <div class="reci-wrapper" style="display: inline-block;">
                     <p id="reci"><?php echo str_replace('receiver.',' ',$message);?></p>
                  </div>  
                  <?php endif ?>

                  <?php if(strpos($message, 'sender.') !== false): ?>
                  <div class="sender-wrapper" style="display: inline-block;">
                     <p id="sender"><?php echo str_replace('sender.',' ',$message);?></p>
                  </div>  
                  <?php endif ?>
               <?php endforeach; ?>

               <?php endif ?>

            <?php endforeach; ?> 
         </div>
         <div class="chatbot-data-wrap">
            <div class="quick-replies">
               <?php if ($order==1): ?>                 
               <button id="order" class="controller">⚡️Order management</button>
               <?php endif; ?>
               <?php if ($customer==1): ?>
               <button id="customer" class="controller">Customer management</button> 
               <?php endif; ?>
               <?php if ($Product==1): ?>
               <button id="product" class="controller">💲Product management</button>
               <?php endif; ?> 
               <?php if ($General==1): ?>
               <button id="generalinquiry" class="controller">General support</button>
               <?php endif; ?> 
            </div>
         </div>
      </div>
      <div class="typing" style="background: rgb(255, 255, 255); border-top-color: rgb(234, 234, 234);">
         <input type="text" id="chat" maxlength="256" placeholder="Type your message here" style="color: rgb(150, 155, 166);"> 
         <button class="mainform">
            <div class="send-icon">
               <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24" xml:space="preserve">
                  <path fill="#d7d7d7" d="M22,11.7V12h-0.1c-0.1,1-17.7,9.5-18.8,9.1c-1.1-0.4,2.4-6.7,3-7.5C6.8,12.9,17.1,12,17.1,12H17c0,0,0-0.2,0-0.2c0,0,0,0,0,0c0-0.4-10.2-1-10.8-1.7c-0.6-0.7-4-7.1-3-7.5C4.3,2.1,22,10.5,22,11.7z"></path>
               </svg>
            </div>
         </button>
      </div>
      <div class="tpl-powered-by frm-footer">
         <span><span style="color: rgb(155, 166, 178);">Powered by</span> 
         <a target="_blank" href="#">Elsner ChatBot</a></span>
      </div>
   </form>
</div>
<script type="text/x-magento-init">
   {
      "*": {
          "myscript": {}
      }
   }
</script>
<script>
   function openForm() {
       document.getElementById("myForm").style.display = "block";
   }
   
   function closeForm() {
     document.getElementById("myForm").style.display = "none";
   }
   
</script>