<?php
/** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
/** @var \Amasty\Shopby\Block\Navigation\FilterRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */

$filterCode = $escaper->escapeHtml($filterSetting->getFilterCode());
$currentCategoryId = (int) $block->getCurrentCategoryId();
?>
<form class="amshopby-flyout-block"
      data-amshopby-filter="<?= /* @noEscape */ $filterCode; ?>"
      data-amshopby-filter-request-var="<?= /* @noEscape */ $block->getFilter()->getRequestVar(); ?>"
      <?php if ($filterSetting->getEnableOverflowScroll() > 0): ?>
            style="max-height:<?= /* @noEscape */ (int) $filterSetting->getEnableOverflowScroll(); ?>px;
            overflow-y: auto;
            overflow-x: hidden;"
      <?php endif; ?>
>
    <ul class="items am-filter-items-<?= /* @noEscape */ $filterCode; ?> amshopby-fly-out-view"
        data-mage-init='{"amShopbyFilterFlyout":{
            "currentCategoryId": "<?= /* @noEscape */ $currentCategoryId; ?>"
        }}'
    >
        <?= /* @noEscape */ $categoryTreeHtml; ?>
    </ul>
</form>
